name: terraform-apply
on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/**"
      - "!**/*.md"

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"

jobs:
  apply:
    environment: dev # optional: use GH Environments for approvals
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-apply-dev
      cancel-in-progress: false
    defaults:
      run:
        shell: bash
        working-directory: infra
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TFSTATE_BUCKET }}" \
            -backend-config="key=${{ secrets.TFSTATE_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Plan (safety)
        run: terraform plan -input=false -out=tfplan.bin

      - name: Apply
        run: terraform apply -input=false -auto-approve tfplan.bin
